### ISSUE TITLE
Data Query link

### ISSUE THREAD

**Issue by lamaqdahodwala** [JBYT27/REPLAPI#16]
Now that I have your attention, I can now say for sure how to use the Replit GraphQL API. Feast your eyes.

https://dgraph.io/docs/graphql/api/requests/

From this documentation: 
>GET requests must be sent in the following format. The query, variables, and operation are sent as URL-encoded query parameters in the URL.

`http://localhost:8080/graphql?query={...}&variables={...}&operation=...`

**Comment by lamaqdahodwala** [comment]
This should help kick start a golden age, and this package can be used as a wrapper for interacting with the GraphQL Api.

**Comment by lamaqdahodwala** [comment]
Hopefully this helps you guys!
~~I'm not gonna do any of the work btw heheheh~~

**Comment by darkdarcool** [comment]
in the module that we use to make the speeds go faster for version 0.0.4(or 0.0.5) we started using a module called `repltalk`, which use all of those things(we know because we accidentally made it print it's source code)

**Comment by darkdarcool** [comment]
(and yes, if dream got 15 min he would beat the world record my 4-5 min)

**Comment by darkdarcool** [comment]
and we can 100% get data from here, lemme pin this

**Comment by lamaqdahodwala** [comment]
Also, here are some examples:
```
{
  userByUsername(username:"darkdarcool"){
    posts {
      items{
        title
        voteCount
        comments(count:10){
          items{
            user{
              username
            }
            voteCount
            body
          }
          
        }
        repl{
          title
          language
        }
      }
    }
  }
}
```
This query will get all the posts of "darkdarcool", and include top 10 comments, the language of the repl that was posted, and the cycle count.

**Comment by lamaqdahodwala** [comment]
```
{
  userByUsername(username:"darkdarcool"){
    publicRepls{
      items{
        language
        title
        size
      }
    }
  }
}
```
This one will get all of "darkdarcool"s repls (that are public)

**Comment by lamaqdahodwala** [comment]
Also, you would be needing some headers. This is what I use:
```
{
  "X-Requested-With": "Yourmom",
  "Referrer": "https://replit.com/"
}
```

**Comment by darkdarcool** [comment]
hmm, ill look into it by tomorrow(or at least before we stop working on this)
