### ISSUE TITLE
You don't really need to use graphql for most of this project

### ISSUE THREAD

**Issue by ch1ck3n-byte** [JBYT27/REPLAPI#18]
i mean everyone uses graphql ok

but https://replit.com/data/profiles/ch1ck3n is so much better (~~no idea why maybe just because i dont understand graphql~~)

but here is my almost-graphql free version of this

https://replit.com/@ch1ck3n/replapi-v2#replapi2/main.py

**Comment by darkdarcool** [comment]
We do eval data from there, but data for graph all is just faster.
