### ISSUE TITLE
Are you thinking of Expanding?

### ISSUE THREAD

**Issue by RayhanADev** [JBYT27/REPLAPI#19]
So I know your project has so far focused on getting *just* user information but are you ever thinking of expanding in the future? I would certainly be able to help if you need help with Post Data :)

**Comment by darkdarcool** [comment]
we would :heart: that! we can add you to this later!(or just make pull requests!)

**Comment by RayhanADev** [comment]
lol I'm already a collaborator, but yeah I'll start a fork and work on it :)

**Comment by darkdarcool** [comment]
cool(i don't remember you being added tho lol)

**Comment by RayhanADev** [comment]
Neither do I ƪ(˘⌣˘)ʃ

**Comment by JBYT27** [comment]
hmmm? oh, i think i did add u lol. sry im not answering any issues. or whatever. lol

**Comment by darkdarcool** [comment]
Ll it’s fine @JBYT27
