### ISSUE TITLE
Installation table

### ISSUE THREAD

**Issue by darkdarcool** [JBYT27/REPLAPI#20]
@RayhanADev, is there anyway to center, having it there annoys the heck outta me

**Comment by RayhanADev** [comment]
Hmmm, center the table?

I can try, but Github Flavored Markdown is super weird.

**Comment by RayhanADev** [comment]
@darkdarcool nope it is impossible, Github sanitizes it and you can only define a table style is <style> tags so nope :(.

**Comment by darkdarcool** [comment]
oh, that sucks :((
