### ISSUE TITLE
a problem :/

### ISSUE THREAD

**Issue by iop3** [JBYT27/REPLAPI#23]
This is my code:
```py
import REPLAPI

REPLAPI.replit_cycles('IOP3')
```

It returns the error:
```
ERROR: Cannot find @IOP3's cycles!
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000027C72C7C940>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

am i doing something wrong? @JBYT27 @darkdarcool

**Comment by darkdarcool** [comment]
The system can't find you, so this isn't an error with the module, just your username, lol

**Comment by iop3** [comment]
oh oops! lol

**Comment by darkdarcool** [comment]
;)

**Comment by JBYT27** [comment]
@darkdarcool, thanks for replying to comment :)

**Comment by darkdarcool** [comment]
your welcome!

**Comment by iop3** [comment]
Also I think that (@)mat-1's [repl-talk-api](https://github.com/mat-1/repl-talk-api) is broken. Cuz I got a error while running [this](https://github.com/80b/repl.it-name-checker) and [that person](https://github.com/80b) used mat-1's repl talk api.

**Comment by iop3** [comment]
And I got the same error while running this repo.

**Comment by iop3** [comment]
@darkdarcool @JBYT27

**Comment by darkdarcool** [comment]
well, this still isn't a replapi problem, maybe try using an older version?

**Comment by iop3** [comment]
ok...

**Comment by iop3** [comment]
wait but you didn't answer my question. What is wrong with this code:
```py
import REPLAPI

REPLAPI.replit_cycles('IOP3')
```

My username is good. I think im using the functions well. But it still returns a error. 💢 ?!!

**Comment by JBYT27** [comment]
Uh, your username isn't exactly IOP3. If you take a look at the screenshot below, it's incorrect. Maybe try 'iop3'?
![Screenshot 2021-06-18 2 21 44 PM](https://user-images.githubusercontent.com/76911308/122602267-899a3080-d040-11eb-88b4-ccdd584e8051.png)

> lol note that im on a school pc with random bookmarks

**Comment by JBYT27** [comment]
Oops, that's a mistake. It could be an inside issue with the code of our module, or Mat1's module, OR it could be a Replit routing error. We'll try to figure it out ASAP. 
Sorry!

**Comment by darkdarcool** [comment]
Well this is probably and internal error, I can try to fix it later

**Comment by JBYT27** [comment]
Got it. Aren't we working on different styling though? For the module?

**Comment by darkdarcool** [comment]
lol yes, but I am smort and saved the original code in a text file :)

**Comment by JBYT27** [comment]
Haha, nice, maybe we should make 1 big class for the json style, and then for the first version we made, just copy and paste it into the regular main file. Like the json style we're doing rn will be in a `json` class, and then the first version will be outside the class.
Think it's nice? or no lol
