### ISSUE TITLE
Why not try the actual Replit GraphQL API?

### ISSUE THREAD

**Issue by RayhanADev** [JBYT27/REPLAPI#7]
Heya! Just your friendly Furret dropping a tip!

Replit has an actual API at [https://replit.com/graphql](https://replit.com/graphql) and the playground is at [https://replit.com/graphql/playground](https://replit.com/graphql/playground). You can try making actual GraphQL queries instead of using middlemen sites and web scraping (it might be simpler too)!

For a (decent) compendium of Replit's GraphQL queries visit my repo REPLAPI.it and you'll find a decent amount of stringed queries in the `src/classes/` folder (and the file names are pretty self-explanatory). 

Feel free to respond with any questions or your thoughts :D

**Comment by darkdarcool** [comment]
Looks good, we will definitely look into it! And you(ferret) can drop in anytime to drop in a suggestion!

**Comment by darkdarcool** [comment]
@RayhanADev, can you give me an example of how to do this in `python`, it have no idea how to do this in python

**Comment by RayhanADev** [comment]
Okay, to my knowledge you can use the requests package to fetch (sorry I'm a JS dev xD). Here's an example for fetching user info:

First install the package:
```bash
python3 -m pip install requests
```

This in the python file:
```py
import requests

requests.post("https://replit.com/graphql", data={ query: "query User($username: String!) { userByUsername(username: $username) { username, karma }", variables: { username: "RayhanADev" } })
```

and that should fetch my cycles. Try it out (and if it throws any Python specific errors, you might know the fix). ![Here's](https://appdividend.com/2020/06/22/python-requests-post-method-example/#:~:text=%20Python%20Requests%20POST%20Method%20Example%20%201,have%20to%20invoke%20requests.post%20%28%29%20method.%20More%20) where I got my information about requests, it might be useful too!

Good luck!

**Comment by darkdarcool** [comment]
lol i understand @RayhanADev(i'm a cpp dev), but it isn't working, I'll try more things tomorrow, but if you have any ideas, keep them coming!

**Comment by darkdarcool** [comment]
@RayhanADev, I got it to work, but, this isn't the desired output:

``` python
import requests
query = None
variables = None
username = None
result = requests.post("https://replit.com/graphql", data={ query: "query User($username: String!) { userByUsername(username: $username) { username, karma }", variables: { username: "RayhanADev" } })

print(result)
```
Result:
```
<Response [403]>
```

**Comment by RayhanADev** [comment]
Oh a 403 error

You may need to set some headers:
```py
import requests
query = None
variables = None
headers = None
username = None
result = requests.post("https://replit.com/graphql", data={ query: "query User($username: String!) { userByUsername(username: $username) { username, karma }", variables: { username: "RayhanADev" } }, headers={ "X-Requested-With": "REPLAPI", "Referrer": "https://replit.com/" } )

json_result = result.json()

print(json_result)
```

**Comment by darkdarcool** [comment]
Hmmm, still doesn't work, but thanks for the info! I'll keep testing them and will 100% ❤️ your ideas and contributions! 

If you get an idea, let me know! 

(also test them out in a replit python repl. cause that is where I am testing them out :)  )

**Comment by RayhanADev** [comment]
Gotcha okay :)

I'll close this for now till I get some more info ~~and Python skill~~

**Comment by JBYT27** [comment]
huh. i didnt see this. but kewl. thnx!

**Comment by darkdarcool** [comment]
@RayhanADev, lol okay, feel free to make a pull request or an issue anytime!
